hmpps-auth:
  url: "http://localhost:8090/auth"

aws:
  s3:
    endpoint: http://host.docker.internal:4566
  sns:
    endpoint: http://localhost:4566
  credentials:
    accessKey: test
    secretKey: test
  region: eu-west-2
  topic-arn:
    events: "arn:aws:sns:eu-west-2:000000000000:hmpps-e-surveillance-dev-person-id-sns-topic"
    file-upload: "arn:aws:sns:eu-west-2:000000000000:hmpps-e-surveillance-dev-file-upload-sns-topic"

end-point:
  ingest: "http://hmpps-e-surveillance-api:8080/ingest/"
  ingest-events: "http://hmpps-e-surveillance-api:8080/ingest/events"

spring:
  datasource:
    url: "jdbc:postgresql://surveillance-db:5432/esurveillance"
    username: myuser
    password: mypassword

hmpps:
  sqs:
    provider: localstack
    queues:
      fileuploadqueue:
        queueName: file-upload-queue
        dlqName: file-upload-dlq
        subscribeTopicId: fileuploadtopic
      personidqueue:
        queueName: person-id-queue
        dlqName: person-id-dlq
        subscribeTopicId: personidtopic
    topics:
      fileuploadtopic:
        arn: arn:aws:sns:eu-west-2:000000000000:file-upload-topic
      personidtopic:
        arn: arn:aws:sns:eu-west-2:000000000000:person-id-topic