hmpps-auth:
  url: "http://localhost:8090/auth"

aws:
  credentials:
    accessKey: test
    secretKey: test
  region: eu-west-2
  s3:
    peopleAndEventsBucket: people-and-events-bucket
    urlExpirationMinutes: 15

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/esurveillance"
    username: myuser
    password: mypassword

hmpps:
  sqs:
    provider: localstack
    queues:
      fileuploadqueue:
        queueName: fileuploadqueue
        dlqName: file-upload-dlq
        subscribeTopicId: fileuploadtopic
      personidqueue:
        queueName: personidqueue
        dlqName: person-id-dlq
        subscribeTopicId: personidtopic
    topics:
      fileuploadtopic:
        arn: arn:aws:sns:eu-west-2:000000000000:file-upload-topic
      personidtopic:
        arn: arn:aws:sns:eu-west-2:000000000000:person-id-topic.fifo

notify:
  api:
    key: "local-fake-api-key"
  templates:
    tamperingWithDevice:
      smsId: "cf6c6c86-4510-4f77-bf70-af4e9979f085"
      emailId: "3ce9cad8-30f4-46b2-a810-00018623025c"
    enteringExclusionZone:
      smsId: "793c8c27-c6f5-47f2-b043-b30043920797"
      emailId: "8938a620-ad4a-4fdc-a3a0-1a63cad87179"
    missingCurfew:
      smsId: "0fd38b72-009e-4cda-b83e-89de6fc372a5"
      emailId: "7f49bf4d-e3ff-4bfd-b0e9-105ae90a381a"
    batteryLow:
      smsId: "22be7ba1-4d7e-4cfa-a556-95573bae0c47"
      emailId: "85bf318d-04c0-4d9b-a516-9683266ceeea"
