hmpps-auth:
  url: "http://localhost:9090/auth"

aws:
  credentials:
    accessKey: test
    secretKey: test
  region: eu-west-2
  s3:
    peopleAndEventsBucket: people-and-events-bucket
    urlExpirationMinutes: 15

spring:
  datasource:
    url: "jdbc:postgresql://surveillance-db:5432/esurveillance"
    username: myuser
    password: mypassword

hmpps:
  sqs:
    provider: localstack
    queues:
      fileuploadqueue:
        queueName: fileuploadqueue
        dlqName: file-upload-dlq
        subscribeTopicId: fileuploadtopic
      personidqueue:
        queueName: personidqueue
        dlqName: person-id-dlq
        subscribeTopicId: personidtopic
    topics:
      fileuploadtopic:
        arn: arn:aws:sns:eu-west-2:000000000000:file-upload-topic
      personidtopic:
        arn: arn:aws:sns:eu-west-2:000000000000:person-id-topic